# Generated by Django 2.2.17 on 2021-01-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraiser',
            name='img',
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(null=True, upload_to='fundraisers/images'),
        ),
    ]
