# Generated by Django 2.2.17 on 2021-01-26 01:51

from django.db import migrations
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210125_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='user_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='fundraiser',
            old_name='user_id',
            new_name='customer_id',
        ),
    ]
