# Generated by Django 2.2.17 on 2021-02-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210224_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='flag',
            field=models.CharField(default='Open', max_length=10, null=True),
        ),
    ]
